#!/usr/bin/env bash

#service_broker_account_id="100000000001"

aws cloudformation create-stack \
    --stack-name AwsServiceBrokerWorkerRole \
    --template-body file://aws-service-broker-worker.json \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameters ParameterKey=ServiceBrokerAccountId,ParameterValue=100000000001 \
    --region us-east-2 \
    --profile stc-one-platform-dev



