kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test2
  name: test2-full-right
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test2-full-right-binding
  namespace: test2
subjects:
- kind: User
  name: test2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: test2-full-right
  apiGroup: rbac.authorization.k8s.io
